name: Build development image
on:
  push:
    branches:
      - main

jobs:
  build_release_image:
    name: Build and release docker image
    steps: 
      - name: Checkout
        # uses: actions/checkout@v3
        run: echo 'test'
          