name: Build development image
on:
  push:
    branches:
      - main
    inputs:
      image_tag:
        description: Tag to images
        type: string
        default: snapshot-artifact
      docker_build_dir:
        description: Docker build directory (default = '.')
        default: "."
        type: string
      path_to_dockerfile:
        description: Path to the dockerfile (default = 'Dockerfile')
        default: "./Dockerfile"
        type: string
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  build_release_image:
    name: Build and release docker image
    runs-on: ubuntu-latest
    steps: 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::237533616493:role/github
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          docker build "${{ inputs.docker_build_dir }}" -f "${{ inputs.path_to_dockerfile }}" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"