name: Build development image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_release_image:
    name: Build and release docker image
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
          